run:
	-killall .eww-wrapped
  
	/nix/store/anvzaqx5vhdx8wvaryb9nz8xifi06x5l-eww-unstable-2023-08-18/bin/eww -c . open bar
	
reload:
	/nix/store/anvzaqx5vhdx8wvaryb9nz8xifi06x5l-eww-unstable-2023-08-18/bin/eww -c . reload

init:
	/nix/store/anvzaqx5vhdx8wvaryb9nz8xifi06x5l-eww-unstable-2023-08-18/bin/eww -c . logs &

inspect: 
	/nix/store/anvzaqx5vhdx8wvaryb9nz8xifi06x5l-eww-unstable-2023-08-18/bin/eww -c . inspector


clean:
	-killall .eww-wrapped
