# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: rec {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "vmd" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cdfe023e-ffdf-4fc5-8e38-8fcf06b6e83a";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/cdfe023e-ffdf-4fc5-8e38-8fcf06b6e83a";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/cdfe023e-ffdf-4fc5-8e38-8fcf06b6e83a";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-uuid/503b9569-dd70-408b-8337-73391a4585cc";
    keyFile = "/luks/swap.key";
    fallbackToPassword = true;
  };

  boot.resumeDevice = "/dev/disk/by-uuid/41c42a83-bee9-4678-85c9-efd0dfb75948";
  swapDevices = [
    {device = boot.resumeDevice;}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
